### ISSUE TITLE
Add more things to the Textbooks page for the demo

### ISSUE THREAD

**Issue by WrightSE** [WrightSE/Hendrix-SOS-Resources#3]
**Describe the incomplete feature**
More information and entries need to be added to the textbooks page for our demo

**Describe what part of the feature is incomplete**
Not enough entries

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Date Due By (if applicable)**
Nov. 12th

**Comment by zachbernheimer** [comment]
Merged commit to add more entries
